name = "Create VC"
author = "Jammersmurph"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd28b3a4a1a8619f9fc9aa21e8db927083cb3be87aad7e2522f0669f720da62a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
