name = "Create VC"
author = "Jammersmurph"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be44b676b3d6ed548c3c1de73e42fb3e6efabe458b8e4ef4d88986705583fa23"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
