name = "Create VC"
author = "Jammersmurph"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64c1c8228ff593186fd1539d1042c6d064427dae9795f73cfa73cd99401683e1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
